name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Setup Node
      uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
