name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
    - name: Setup Node
      uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
